"""finish all tbl

Revision ID: 6e023f348f69
Revises: 4a7e393bedee
Create Date: 2021-11-28 19:14:54.695585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e023f348f69'
down_revision = '4a7e393bedee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Language',
    sa.Column('languageid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('description', sa.String(), server_default="C'est belle comme langue", nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['User.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('languageid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SpokenLanguage',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('LanguageID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['LanguageID'], ['Language.languageid'], ),
    sa.ForeignKeyConstraint(['UserID'], ['User.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('UserID', 'LanguageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SpokenLanguage')
    op.drop_table('Language')
    op.drop_table('User')
    # ### end Alembic commands ###
