name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name : update pip
        run: python -m pip install --upgrade pip
      - name: dependencies
        run: pip install -r requirements.txt
      - name: pytests
        run: |
          pip install pytest
          pytest 


